version: 2

updates:
  - package-ecosystem: 'docker'
    directory: '/'
    reviewers:
      - 'bzzim'
    assignees:
      - 'bzzim'
  - package-ecosystem: 'github-actions'
    directory: '/'
    reviewers:
      - 'bzzim'
    assignees:
      - 'bzzim'
